# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '03_Project02_Guess the Flag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 03_Project02_Guess the Flag

pod 'SPAlert'

end
