# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '01_Project01_WeSplit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_Project01_WeSplit

pod 'Introspect'

end
