# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '07_Project05_WordScramble' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 07_Project05_WordScramble

pod 'Introspect'

end
